server:
  port: 9001

spring:
  application:
    name: eureka-client1
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8700/eureka/

#  instance:
#    hostname: demo-spring-cloud-app-springclouddemo.azuremicroservices.io
#    secure-port-enabled: true
#    nonsecure-port-enabled: false
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:443
#    status-page-url: https://${eureka.hostname}:443/actuator/info
#    health-check-url: https://${eureka.hostname}:443/actuator/health
#    secure-health-check-url: https://${eureka.hostname}:443/actuator/health
#    non-secure-port: 80
#    secure-port: 443