server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ibinsigma/springcloud-config-repository.git
          search-paths:
            - configuration/{application}/
            - configuration/

eureka:
  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8700/eureka/

#spring:
#  application:
#    name: cloud-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/ibinsigma/springcloud-config-repository.git


#eureka:
#  client:
#    registry-fetch-interval-seconds: 5
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: https://demo-spring-cloud-app-springclouddemo.azuremicroservices.io/eureka
#  instance:
#    hostname: demo-spring-cloud-app-springclouddemo.azuremicroservices.io
#    secure-port-enabled: true
#    nonsecure-port-enabled: false
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:443
#    status-page-url: https://${eureka.hostname}:443/actuator/info
#    health-check-url: https://${eureka.hostname}:443/actuator/health
#    secure-health-check-url: https://${eureka.hostname}:443/actuator/health
#    non-secure-port: 80
#    secure-port: 443
